### ISSUE TITLE
assigned_to deserialize

### ISSUE THREAD

**Issue by RafaelCavazza** [intercom/intercom-dotnet#101]
Why the 'assigned_to' attribute in the ConversationPart class is a string in the bv/netstandard2.0 branch?

It shouldn't be 'Assignee'?

![image](https://user-images.githubusercontent.com/8078357/36219907-084d925e-11a0-11e8-9356-ba74481d053d.png)

![image](https://user-images.githubusercontent.com/8078357/36219940-23490ec6-11a0-11e8-9b33-099d4718c2eb.png)

When I tried to run the netstandard2.0 branch i've got the folowing erro:
`Newtonsoft.Json.JsonReaderException : Unexpected character encountered while parsing value: {. Path '[0].assigned_to', line 10, position 20.`

Then i verified that the 'assigned_to' attribute is a object. When I changed it from string to Assignee it worked.

**Comment by kmossco** [comment]
Hey @RafaelCavazza! Thank you so much for reporting this, seems like this is wrong indeed. I tested this based on the conversation part model in our API reference [here](https://developers.intercom.com/reference#conversation-part-model):

<img width="636" alt="image" src="https://user-images.githubusercontent.com/11810153/36229671-f15f7bd6-11cf-11e8-8ecf-68d0008e46b7.png">

But I think my testing may have been wrong. I'll look into this and make a change this week. Let me know if you find any other problems, and thank you for testing this!

**Comment by kmossco** [comment]
This is now fixed here: https://github.com/intercom/intercom-dotnet/pull/97/files#diff-aa05218441e91c417e15908edaec2380R17. And will update the documentation so the API reference reflects what is returned. 👍 Thanks once again!

**Comment by RafaelCavazza** [comment]
Hi @kmossco!

Thanks for the response!

We are developing a integration using the bv/netstandard2.0 branch.
We are migrating to the Net Core envioroment and will be using some of the API functionality.

I'll report any bug, issue or improvement we find.

We hope to see soon the .netStandard2.0 package in your nuget.

Best Regards!

**Comment by kmossco** [comment]
Glad to hear it!  🎉We are currently working on getting it peer reviewed to ensure we don't break anyone's workflow, and hopefully we will have a release very soon!

And if you spot anything missing, a bug or have any feedback we are all 👂s!
