### ISSUE TITLE
Company website not updated when creating a company in a user create/update call

### ISSUE THREAD

**Issue by thewheat** [intercom/intercom-dotnet#108]
- If you supply company details when making a user create/update call, it does not update the website attribute on the company
- Sending a company website in this manner **is supported via the API** using a raw API call with the following data (which correctly updates the website on a company)
```
{
	"user_id": "1",
	"companies": [
	{
		"id": 1, 
		"name": "Company 1", 
		"website": "http://www.company1.com"
	}]
}
```
- But using the following with the .NET library does not update the company website
   - It does update the company name though (so it is processing the data correctly but just not picking up all fields)
```
            UsersClient usersClient = new UsersClient(new Authentication(TOKEN));
            Company c = new Company { website = "http://company1take2.com", company_id = "1", name = "Co 1" };
            List<Company> companies = new List<Company>();
            companies.Add(c);
            usersClient.Create(new User { user_id = "1", name = "User 1",
            	companies = companies
            });
```

Using the latest 1.0.31 version available: https://www.nuget.org/packages/Intercom.Dotnet.Client/
![image](https://user-images.githubusercontent.com/892961/38282919-6cdf297e-37e5-11e8-88bb-446287ed2f79.png)

Other company fields will likely be affected like size and industry as indicated by this PR https://github.com/intercom/intercom-dotnet/pull/86

**Comment by kmossco** [comment]
The problem seems to be how we construct the JSON body for the requests and needs to be overhauled. I believe the problem is here:

https://github.com/intercom/intercom-dotnet/blob/7d2dff504425daa797ceb8bf2d91af2049fa25ba/src/Intercom/Clients/UsersClient.cs#L407-L442

So even if you send more details than the ones there in this method, they won't be sent. 😞
