### ISSUE TITLE
Getting authorization error

### ISSUE THREAD

**Issue by adeelhasan** [intercom/intercom-dotnet#109]
Hi,

Without a code change at our end, we started to see the following error :

`{\"type\":\"error.list\",\"request_id\":\"b2jiv6iroeecej5qclm0\",\"errors\":[{\"code\":\"token_suspended\",\"message\":\"Unauthorized token, suspended application\"}]}`

I have verified that the token is correct : have made successful api calls in Python and we are also able to use the application fine.

I talked to Intercom support, and they could only verify that the token was valid (they made curl calls at their end.)

Any idea under what circumstances this error will start to come up? From our own logs, this began around Feb 20th, so went unnoticed for a bit.

thanks

**Comment by kmossco** [comment]
Hey @adeelhasan! It seems that your app has been suspended, so this is not a problem with the library itself. Can you try reaching out to our support team for us to investigate this further? You can find us either using the Messenger when logged in to Intercom, or by emailing us at team[at]intercom.io.

**Comment by adeelhasan** [comment]
thanks for replying. as mentioned in the ticket, I am able to make calls using Python with the same token, from the same machine as I am getting the error with the SDK. Intercom support verified too, by doing a CURL with the same token.  So if the app was suspended, the Python call should have failed too. For some reason using the SDK or using a call with the .net webclient -- basically a call from the .NET CLR is giving this particular error.

So it could be that there is some issue with eg. TLS 1.2 or some other network upgrade that could have happened on Intercom's side and with which there is an incompatibility. That said, if it were a widely applicable problem, someone else should have reported it as well.

what would be very helpful to know is under what circumstances would the Intercom API give this error. thank you.

**Comment by kmossco** [comment]
I checked with our team and it seems that the problem was indeed an incorrect token, so I'll leave this closed. I hope that solves it and ping us if you spot any other problems.
