### ISSUE TITLE
UsersClient incorrectly uses id / user_id

### ISSUE THREAD

**Issue by DannyWatkins** [intercom/intercom-dotnet#11]
Several of the update methods incorrectly post id rather than user_id or vice versa. For example UpdateLastSeenAt(User user) has this line : 

String body = JsonConvert.SerializeObject(new { user_id = user.id, update_last_request_at = true });

Note the assignment of user_id = user.id rather than user_id = user.user_id.

These errors are widespread and inconsistent in the UsersClient, making the library currently unusable for basic user updates.

**Comment by khalilovcmd** [comment]
Thank you @DannyWatkins for reporting this issue 👍  

I have applied a hot fix #12 for the `UsersClient` and please let me know if it is works as expected. We are also updating our developers docs to have a better explanation for the `UpdateLastSeenAt`.

**Comment by khalilovcmd** [comment]
You can get the latest Nuget version from [here](https://www.nuget.org/packages/Intercom.Dotnet.Client/) `1.0.5`.

**Comment by DannyWatkins** [comment]
Many thanks for the quick turnaround Tarek.

 

I’m not in a position to test the fix today but having scanned down the file it now looks fine.

 

Thanks again

 

Danny.

**Comment by khalilovcmd** [comment]
You are welcome @DannyWatkins , you can always ping us here for any more issues 👍

**Comment by DannyWatkins** [comment]
Hi Tarek, 

 

We probably won’t be using the wrapper going forward but I just wanted to help you with a discovery today.

 

The IncrementUserSession doesn’t appear to work beyond the first session. After struggling with this I see that the documentation says you should set the new_session flag “while updating the user record”. 

 

Having experimented it appears that the new_session flag is ignored unless there is something else to update. 

 

So in our own implementation we combine a number of updates in one call, including “new_session = true”, and this successfully updates the session count. This is a little tricky to test because there is also a 30 minute minimum period between new sessions.

 

I hope this helps you get IncrementUserSession working for other users.

 

Best regards

 

Danny.
