### ISSUE TITLE
Conversation model field "conversation_parts" is always null despite it shouldn't

### ISSUE THREAD

**Issue by Fahrenheit9292** [intercom/intercom-dotnet#113]
I have a problem regarding API conversation model: on your reference I could see this is the Object that contains conversation_parts Object
Now when I try to get the Conversation object from JSON I always get the conversation_parts object with null value despite it has the value when using the Postman request
conversation ID as example
**15673691858**
![image](https://user-images.githubusercontent.com/38457029/38858114-8dd9d5d6-4233-11e8-9377-9e4f9c255542.png)
that's how conversation_parts object does look like on Postman response
![image](https://user-images.githubusercontent.com/38457029/38858143-99d1bb9c-4233-11e8-8786-bbb67e9f4138.png)
and on the project it's null

I know that on your SDK model conversation_parts field is not object, but List<ConversationPart>, however it didn't work as well.

**Comment by Fahrenheit9292** [comment]
Hey there,
I'm using the 2.0 .NET SDK that is now available on GitHub.

Best regards,
Andrey

**Comment by Fahrenheit9292** [comment]
Hey there,
did you figure this out?

**Comment by Fahrenheit9292** [comment]
![2018-05-03_10-31-26](https://user-images.githubusercontent.com/38457029/39564502-30202a8a-4ebd-11e8-8238-4429329f00a3.png)
![2018-05-03_10-32-42](https://user-images.githubusercontent.com/38457029/39564547-574581aa-4ebd-11e8-9e3e-57ed709d8bdd.png)
I'm pretty sure the problem here is with JsonConverter used for the fields "tags" and "conversation_parts" on the "Conversation" Object

**Comment by Fahrenheit9292** [comment]
as you can see, the tags field is null for the conversation on c# and not null on Postman response for the same conversation

**Comment by kmossco** [comment]
Hey @Fahrenheit9292, sorry for the delay but I think I got this resolved in PR #132. I am looking to merge it next week, but if you want to give it a try in the meantime let me know if you bump into any issues with it.
