### ISSUE TITLE
Company monthly_spend is an int instead of decimal

### ISSUE THREAD

**Issue by xdansmith** [intercom/intercom-dotnet#117]
Can monthly_spend be changed back to a decimal so accurate monthly fees can be stored, like `1.95`?

**Comment by DotJoshJohnson** [comment]
The Intercom API only supports integer values in `monthly_spend`.

**Comment by xdansmith** [comment]
What is the correct way to map an amount with cents like 1.95 in that case, or is it not possible?

**Comment by DotJoshJohnson** [comment]
As far as I know, that would have to be stored in a custom attribute:

```csharp
decimal monthlyFees = 1.95;
company.custom_attributes["monthly_fees"] = monthlyFees;
```

In the Intercom app, you can then leverage that attribute in pretty much the same way in terms of filtering, qualification, etc.

**Comment by kmossco** [comment]
Hey @xdansmith, thank you for bringing this up. Not quite sure which is the expected behaviour and this week I am away from any work on the API, but early next week I'll do some testing and ensure we match the type that the API accepts from curl for full feature parity. 👍

**Comment by kmossco** [comment]
I checked with the team and it seems that we accept Floats:

![image](https://user-images.githubusercontent.com/11810153/41493529-0cb951c4-7100-11e8-94a1-f406a32d275f.png)

However they will be truncated. I made this change already, can one of you review it? https://github.com/intercom/intercom-dotnet/pull/129
