### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by nadeem-edgylabs** [intercom/intercom-dotnet#120]
Intercom has recently updated their API to include the functionality to permanently delete a user or lead to comply with the new GDPR regulations. The previous API just archives the user, Is there any update on this functionally? 
Here is reference document,
https://docs.intercom.com/faqs-and-troubleshooting/your-users-and-leads-data-in-intercom/how-do-i-delete-users-and-leads-in-intercom

**Comment by kmossco** [comment]
Closed with release [2.1.0](https://github.com/intercom/intercom-dotnet/releases/tag/2.1.0).
