### ISSUE TITLE
Missing Count property on Segment

### ISSUE THREAD

**Issue by ThomasArdal** [intercom/intercom-dotnet#122]
In the API, Segments have a `count` attribute. This attribute is never mapped to a property on the `Segment` object. I've talked with Intercom support, who tell me that it is because `count` wasn't available in the previous versions of the API.

**Comment by kmossco** [comment]
You're right, this is missing. We are having a few woes with the transition to DotnetStandard but I'll try to squeeze this in asap. 

![image](https://user-images.githubusercontent.com/11810153/40250265-ae1debd6-5acd-11e8-9d89-7f1b964101bf.png)

However if anyone has the time to send us a PR I'll be happy to review it.

**Comment by ThomasArdal** [comment]
How would you prefer the include_count parameter to be set?

Could be always:

    result = Get<Segment>(parameters: new Dictionary<string, string> { { "include_count", "true" } }, resource: SEGMENTS_RESOURCE + Path.DirectorySeparatorChar + id);

Through a parameter on the View-method:

    public Segment View(String id, includeCount = false)

Or something third?

**Comment by ThomasArdal** [comment]
@kmossco

**Comment by kmossco** [comment]
@ThomasArdal so sorry for the delay here, completely missed this one. 😞 I think that the second option would make more sense as it's the pattern we already have for other endpoints like Scroll:

https://github.com/intercom/intercom-dotnet/blob/04fc9d7082641bc6089070d9147e5f6b1feef1eb/src/Intercom/Clients/ContactsClient.cs#L134-L145

How does that sound?

**Comment by ThomasArdal** [comment]
No problem :smile:

There you go: https://github.com/intercom/intercom-dotnet/pull/126

**Comment by kmossco** [comment]
This is awesome! 🎉 Thank you so much. We are having a few issues with our Nuget package build and so PRs are a bit delayed, but as soon as we fix that I'll review your PR and add it to the next release. 👍

**Comment by kmossco** [comment]
Closed with release [2.1.0](https://github.com/intercom/intercom-dotnet/releases/tag/2.1.0).
