### ISSUE TITLE
.Net 4.6 Support

### ISSUE THREAD

**Issue by steve-tapley** [intercom/intercom-dotnet#125]
Hi,
I'm upgrading from 1.0.31 to 2.0.0 and came across this error:

`
Could not install package 'Intercom.Dotnet.Client 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

I sure hope this wasn't intentional :)

Cheers,
Steve

**Comment by kmossco** [comment]
Hey @steve-tapley! So sorry for this, we have accidentally pushed a version to NuGet that has the wrong version and shows as 2.0.0 when it should be a pre-release of 2.0.3-beta. This new major version only supports NetStandard2.0 and this is why you are having this problem. 

Can you please revert back to 1.0.31 which is the last available version for the .Net Framework 4.6?

**Comment by steve-tapley** [comment]
Sure, no worries...I assumed it was a mistake!

Correct me if I'm wrong, but I think you can still target to 4.6 as well as .Net standard 2.0 as 4.6 is a superset of .Net standard 2.0??

**Comment by kmossco** [comment]
I think it only supports 4.6.1 and onwards: https://docs.microsoft.com/en-us/dotnet/standard/net-standard. Could that be it?

**Comment by steve-tapley** [comment]
Yep, that does seem to be a partial solution.

When I set the project to 4.6.1 and updated intercom, it worked but it added about 50 (yes 50!) references to .NET Standard libraries. I think it is possible to target both, as the MSDN docs do show things like this in their csproj files...
`
<Project Sdk=”Microsoft.NET.Sdk”> 
 <PropertyGroup>
 <TargetFrameworks>netstandard1.3;net46</TargetFrameworks>
 </PropertyGroup>
</Project>
`

Anyway, I'll keep using 1.0.31 for the time being.
Good luck!

**Comment by kmossco** [comment]
I really wish I could say we would support net46, however we are already stretched quite thin as it is and it's hard to rally resources when something breaks like this problem we are having pushing the new version out to Nuget. So with that in mind we really won't be able to support anything below or parallel to NetStandard 2.0 for the time being.

But if you bump into any issues with 1.0.31 we'll be happy to help!
