### ISSUE TITLE
Make it available for .NET Framework 4.6.1

### ISSUE THREAD

**Issue by agamanyuk** [intercom/intercom-dotnet#137]
Can you please make a version for .NET Framework 4.6.1? Nobody's using .NET Standard.

**Comment by wil55n** [comment]
Yes please, we're having alot of issues using 2.x with .Net Framework projects.

**Comment by jpasichnyk** [comment]
I believe it should be built against both netstandard2.0 and net45 for compatibility with those moving over to .NET Core as well as those not.

**Comment by CarloSaccone** [comment]
I think that there should be 2 different package for .net core and .net >4.5. 
Tried to nuget on an existing webapi .net 4.6.1 and it broke all the references in the project. Tried to clean it up and leaving just the reference to restsharp, but no luck.

**Comment by jpasichnyk** [comment]
I just created a pull request which multi-targets the SDK against both the existing "netstandard2.0" and as well as "net452" (which i believe should allow >= 4.5.2 to use it). 

Intercom maintainer, please review/merge the pull request: https://github.com/intercom/intercom-dotnet/pull/147

**Comment by lindeberg** [comment]
Any progress?

**Comment by lloydliyu** [comment]
Hey @jpasichnyk :wave:

It looks like this was solved since https://github.com/intercom/intercom-dotnet/pull/147 was merged. If that isn't the case feel free to reopen this.
