### ISSUE TITLE
usersClient.List returns null 

### ISSUE THREAD

**Issue by nadeem-edgylabs** [intercom/intercom-dotnet#141]
With .net version 4.5, this list method is returning the null value. I've tested this API with POSTMAN and it is working fine but when we use this list method it returns null.

**Comment by mzammitkg** [comment]
@nadeem-edgylabs  Should be the same issue as #140.

**Comment by lloydliyu** [comment]
Closing this as out as a duplicate to https://github.com/intercom/intercom-dotnet/issues/140
