### ISSUE TITLE
Xamarin Push Notification Support

### ISSUE THREAD

**Issue by alexshikov** [intercom/intercom-dotnet#154]
As the library supports .Net Standard 2.0 and so that can be used in Xamarin projects it would be nice to extend it with Push Notification feature:

- allow registering device token
- handle incoming push notifications

**Comment by lloydliyu** [comment]
Hey @alexshikov :wave: This seems a little out of scope of this project as the SDK is intended purely to provide .Net bindings to the Intercom API and the API itself doesn't support that.

That said, If this is something you'd like to see, I'd recommend reaching out to the support team using the Messenger on https://intercom.com who'd be able to log this as a feature request for you.
