### ISSUE TITLE
Access to Rate Limit Info

### ISSUE THREAD

**Issue by markalanevans** [intercom/intercom-dotnet#17]
Hey Guys,

Since you don't have the bulk API logic done just yet, is there any way to get access to the Rate Limit Data?

https://developers.intercom.io/reference#rate-limiting

**Comment by khalilovcmd** [comment]
Hey @markalanevans , we are not exposing the Rate Limit as the return objects are of either type `Model` or `Models` which encapsulates and returns the data object only.

**Comment by markalanevans** [comment]
Gotcha. So are you suggesting if we wanted to get Rate Limit info that we create our own class?  I believe we would just need access to a response header object on the client.

What would you suggest?

**Comment by khalilovcmd** [comment]
Yes, that's a good suggestion. Just throwing some ideas out here to expose the HTTP Response (without breaking the client public API):

In two steps, we can do:

1. We could expose an optional `Configuration` parameter in the `Client` class' constructor. The `Configuration` object could have a boolean property `ExposeHeaders` or even `ExposeRateLimit`. The default of any of these two properties would be false.

2. Change the `Model`, and `Models` classes to have a property that contain the `Headers`, `ResponseBody`, and any other relevant HTTP Response information that could be exposed. By default, these properties will be null, unless we provide a `Configuration` object with the parameters I just mentioned above.

**Comment by markalanevans** [comment]
@khalilovcmd currently what happens if a rate limit is hit?

What is the expected workflow?

**Comment by markalanevans** [comment]
It looks like you throw an exception and "rate_limit_exceeded" would be in the list of errors.

Is that correct?

**Comment by khalilovcmd** [comment]
Yes Mark, that's right. If you exceed the rate limit, we receive an error response from the API and then the `Client` will throw an exception along with the information for the errors received (which in this case is the `rate_limit_exceeded`.

**Comment by travega** [comment]
Closing issue as not response since June.

**Comment by frankfuu** [comment]
Any developments on this front?
