### ISSUE TITLE
read messages sent from admin to a user

### ISSUE THREAD

**Issue by mahesh0919** [intercom/intercom-dotnet#2]
Hi I am using previous version of intercom-dotnet (1.0.0.0) in my application to read messages sent from intercom to a user.now I am upgrading your library.

could you please le me know is there any API which provides reading messages sent from intercom to a user. or what is the equivalent API for the below code. code taken from previous version of intercom-dotnet.dll
This will read messages sent to user from intercom.

public dynamic Get(int? user_id = null, string email = null, int? thread_id = null, string current_url = null)
{
			return base.Client.Execute("users/message_threads", 0, delegate(RestRequest request)
			{
				if (thread_id.HasValue)
				{
					request.AddParameter("thread_id", thread_id);
				}
				if (email != null)
				{
					request.AddParameter("email", email);
				}
				if (user_id.HasValue)
				{
					request.AddParameter("user_id", user_id.Value);
				}
				if (current_url != null)
				{
					request.AddParameter("current_url", current_url);
				}
			});
		}

**Comment by khalilovcmd** [comment]
Hey @mahesh0919 , 

As a note, Please use the latest [nuget version 1.0.1](https://www.nuget.org/packages/Intercom.Dotnet.Client/1.0.1)

You can user's conversations by doing the following:
```
UserConversationsClient client = new UserConversationsClient(new Authentication("AppId", "AppKey"));
Conversations conversations = client.List(intercomUserId: user_id_delivery);

foreach(Conversation conv in conversations.conversations)
                    Console.WriteLine(conv.conversation_message.body);
```

We will also write this down in our documentation `Usage` section.

Thank you for raising the issue!
