### ISSUE TITLE
Add Company to a User

### ISSUE THREAD

**Issue by EdBlankenship** [intercom/intercom-dotnet#21]
On the `UsersClient`, it looks like you have a method for removing a company 

`UsersClient.RemoveCompanyFromUser`

Do you have a corresponding method for adding an existing company to an existing user?

**Comment by khalilovcmd** [comment]
Yes, you could this by an `update` to the user through the `UsersClient`. It works just like any other update operations happens. Let me know if this helps 😃

**Comment by EdBlankenship** [comment]
That's the other route we attempted but we're getting `ApiException`s thrown unfortunately by calling the `update` method.  We've sent Tarek the details of attempting to go that route since there isn't an `AddCompanyToUser` method.

**Comment by khalilovcmd** [comment]
Can you please give it a try with the latest [Nuget](https://www.nuget.org/packages/Intercom.Dotnet.Client/) version.

**Comment by EdBlankenship** [comment]
No problem.  Updated our version and removed the binding that was added to the app.config after upgrading and we're still hitting the `ApiException` on the same line as before unfortunately.

**Comment by EdBlankenship** [comment]
Nice!  The latest updates made today resolved the issue. Thank you @khalilovcmd!
