### ISSUE TITLE
Can't set plan on company

### ISSUE THREAD

**Issue by rodball** [intercom/intercom-dotnet#24]
If I pass a plan with the company when updating a user, it never updates the plan information.  If I try to pass the plan and update the company directly, I get the following returned:

{"type":"error.list","request_id":"am16gofh0r4q47mltc0g","errors":[{"code":"parameter_invalid","message":"found unpermitted parameter: plan"}]}

Code is pretty simple:

            Company company = new Company()
            {
                id = companyData.CompanyID.ToString(),
                name = companyData.PreferredCompanyName,
                plan = new Plan() {
                    id = companyData.CompanyPackage.PackageID.ToString(),
                    name = BrandBusinessFacade.GetPackageName(companyData.CompanyPackage.PackageID)
                },
                remote_created_at = companyData.CreateDateTime.ToUnixTimestamp()
            };

            companyClient.Update(company);

**Comment by rodball** [comment]
After updating for nuget, I don't get the error anymore but it still doesn't update plan information for a company.  I've also added a custom attribute that is not updating either.

**Comment by khalilovcmd** [comment]
Have you updated to nuget version `1.0.12`? And if so, do you mind trying again (company updates might take few seconds to be refreshed).

**Comment by rodball** [comment]
Yes, I had updated to version 1.0.12.  I waited several minutes for it to refresh but it never did.

**Comment by khalilovcmd** [comment]
I just noticed this line `id = companyData.CompanyID.ToString(),`
This should be `company_id = companyData.CompanyID.ToString(),` as per the developers docs. Please give it a try.

**Comment by rodball** [comment]
I'm sure that's it.  Missed it.  I'll give it try.  Thanks!

**Comment by khalilovcmd** [comment]
Let me know if it works, so we can close the issue 👍

**Comment by rodball** [comment]
That did it!
