### ISSUE TITLE
Add Support for Personal Token Auth

### ISSUE THREAD

**Issue by markalanevans** [intercom/intercom-dotnet#28]
Looks like we need to start migrating to use Personal Tokens: https://developers.intercom.io/v2.0/docs/personal-access-tokens

Let us know when you add this to the sdk and we will update our end.

**Comment by khalilovcmd** [comment]
Hello @markalanevans , I have released a new nuget version `1.0.16` which supports PAT 👍

**Comment by markalanevans** [comment]
Awesome! Thank you.
