### ISSUE TITLE
Xamarin / Android Package install

### ISSUE THREAD

**Issue by adamrhunter** [intercom/intercom-dotnet#37]
Hi,
When trying to install the Intercom 1.0.18 package into a Xamarin (6.1) Android application, I get the following error (from the Packages Console)

Could not install package 'Intercom.Dotnet.Client 1.0.18'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thanks

**Comment by khalilovcmd** [comment]
Hey @adamrhunter , sorry for the super late reply. Can you please look here? https://github.com/intercom/intercom-dotnet/issues/40

**Comment by choran** [comment]
Hi @adamrhunter 
Would it be best to track this under #40 as indicated above?
For now I will close this since it has been open for a while and we can continue to track it under #40 
But feel free to re-open if you think it is worth keeping this open as well
Thanks
Cathal
