### ISSUE TITLE
Does this one support Xamarin iOS now?

### ISSUE THREAD

**Issue by alexliubj** [intercom/intercom-dotnet#40]

**Comment by alexliubj** [comment]
I'm getting this issue when I was trying to install it from Nugets

Could not install package 'Intercom.Dotnet.Client 1.0.19'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by alexliubj** [comment]
Package 'Intercom.Dotnet.Client.1.0.18 : Newtonsoft.Json [8.0.3, ), RestSharp [105.2.3, )' does not exist in folder 

But I do have them installed.

**Comment by khalilovcmd** [comment]
Hey @alexliubj , sorry for the late reply. We are not yet supporting building the assemblies for Xamarin, but it is something that's definitely on our minds.

**Comment by michael-watson** [comment]
Pull Request #62 removes the RestSharp dependency and should allow the SDK to be installed into PCL profiles. This will enable the SDK to be used in Xamarin.iOS, Xamarin.Android and Xamarin.Forms projects. 

If we can test PR #62 and verify everything works fine, this will enable a lot of Xamarin developers. Of course, there still won't be an implementation of the messenger for Xamarin, but it's a start.

**Comment by choran** [comment]
Hi @michael-watson 
Thanks for this, we will try and review this. As noted, it is something that we are thinking about but it is not the highest priority at the moment. But if the PR helps we will defo try and take a look at that asap and see if we can merge it.
Thanks again
Cathal

**Comment by alexeyzimarev** [comment]
@choran RestSharp 106 and Newtonsoft.Json both support .NET Standard 2.0, so this might be not that hard.

**Comment by alexeyzimarev** [comment]
@michael-watson I would avoid PCL at all costs and move to .NET Standard as soon as possible. I am not sure about the current status of Xamarin but I am quite certain that this is where it is going.

**Comment by kmossco** [comment]
We agree with @alexeyzimarev in that it's best if we move to .NET Standard 2.0 and we have now prioritised this work on #90.
