### ISSUE TITLE
DotNetCore support

### ISSUE THREAD

**Issue by 0xdeafcafe** [intercom/intercom-dotnet#43]
Have you looked into adding dotnet core support? Specifically the .NET Standard - https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

**Comment by 0xdeafcafe** [comment]
I forked the project and added dotnet-core support. I had to make some changes to allow for this - such as replacing `RestSharp` with `System.Net.Http`, although imo this is a much better decision as `RestSharp` is a dead project with no support anymore. I didn't port the tests, and for that reason am not submitting a pull request.

https://github.com/HelmGlobal/intercom-dotnet

**Comment by khalilovcmd** [comment]
@0xdeafcafe that sounds great and sorry for the late reply. We were actually having this in our mind for a long time now. What would you say if you submit a PR, and we work on this together?

**Comment by 0xdeafcafe** [comment]
Sounds good to me.

**Comment by PaulColeman** [comment]
Any update on dotnetcore support?

**Comment by 0xdeafcafe** [comment]
Sorry, I don't work at the company that I had to build this for so I'm not personally working on it anymore.

**Comment by choran** [comment]
Hi All, 
Just wanted to update here, this is something we are interested in doing but at the moment it is not our main priority for the SDK. We are focused on working through the PRs and identifying the other API feature that may be needed in the SDK before getting to this.
Just wanted to provide an update,
Thanks
Cathal

**Comment by Nicholi** [comment]
RestSharp is working on their netstandard support, they currently have pre-release packages available. No real modifications are necessary for intercom-dotnet. Everything seems to be working with the latest RestSharp pre-release, but I wouldn't call it stable until RestSharp does.

I made a fork myself, and updated to latest nunit at same time. All of the modifications were just fixing deprecated nunit things. All the calls I'm using seem to be ok so far.

https://github.com/Nicholi/intercom-dotnet/tree/netstandard20

**Comment by choran** [comment]
Hi @Nicholi 
Thanks for the update. I was not aware of that. We can look into this some more as well to see what needs to be done. If, like you said, no major changes need to be made then it would be good.
Thanks again
Cathal

**Comment by alexeyzimarev** [comment]
@choran RestSharp is released with .NET Standard 2.0 a couple of weeks ago. I get messages that it breaks the intercom.io library. If you need help - please let me know.

**Comment by kmossco** [comment]
Thanks to the feedback in this issue we have now prioritised this work. To keep things clearer, I have closed all the issues related to this support so we can keep the discussion here: #90

**Comment by kmossco** [comment]
@alexeyzimarev thank you so much for the help. We'll definitely let you know if we bump into any issues. 👍
