### ISSUE TITLE
Fix Conversation Tags

### ISSUE THREAD

**Issue by JnelsonEmarketer** [intercom/intercom-dotnet#44]
Conversation tags do not show up when using the Conversation.View(id)
- Problem with Intercom.Data.Conversation.cs?
  
     `public List<Tags> tags { get; set; }` should be `public List<Tag> tags { get; set; }` ?

**Comment by khalilovcmd** [comment]
Hey @JnelsonEmarketer , sorry for the late reply. It is probably an issue during the `deserialisation`, I will check it out 👍

**Comment by JnelsonEmarketer** [comment]
Thanks :)
