### ISSUE TITLE
Why are created_at and signed_up_at on the User class nullable ints and not longs?

### ISSUE THREAD

**Issue by julipur** [intercom/intercom-dotnet#46]

**Comment by khalilovcmd** [comment]
Thank you for your question @julipur 

Int32.Max in .NET is `2147483647`. The current time since epoch is `1478623294`. We will only reach the Int32.Max in year **2038**.

I think it will be more accurate if we have it as **UInt32**.

**Comment by julipur** [comment]
So as long as I cast it down, I'm good. Thanks.

**Comment by khalilovcmd** [comment]
@julipur Yes 👍  but it might throw an Exception if you try and cast a larger value that could be fit into an Int32.
