### ISSUE TITLE
Sending dates as custom_attribute

### ISSUE THREAD

**Issue by robfarmergt** [intercom/intercom-dotnet#52]
What is the correct way to send a `custom_attribute` so that Intercom recognizes it as a **date**? I've tried Unix timestamp as an `int` as well as a `DateTime` object but intercom shows the integer value or datetime json string respectively.

**Comment by EdBlankenship** [comment]
@robfarmergt I believe that you need to make sure that the attribute name ends with `_as` as well.

**Comment by choran** [comment]
HI @robfarmergt 
Yeah, if your custom attribute ends with '_at' we will treat it as a timestamp.
You can find out more from our API ref page [here](https://developers.intercom.com/reference#section-custom-attributes)
I will close this for now but please re-open if you are still having issues with this.
Thanks
Cathal

**Comment by DanOrsborne** [comment]
I can't get this to work!  Any pointers?
