### ISSUE TITLE
Cannot obtain Notes by user_id

### ISSUE THREAD

**Issue by rogerhelliwell** [intercom/intercom-dotnet#58]
We can retrieve notes by id, email or user_id. When using user_id, Intercom returns a "User not found" error. I've looked at the NotesClient code. There is an error in the List method around line 157.

else if (!String.IsNullOrEmpty(user.user_id))
            {
                parameters.Add(Constants.USER_ID, user.id);
                result = Get<Notes>(parameters: parameters);
            }

.... should be...

else if (!String.IsNullOrEmpty(user.user_id))
            {
                parameters.Add(Constants.USER_ID, **user.user_id**);
                result = Get<Notes>(parameters: parameters);
            }

**Comment by choran** [comment]
Hi @rogerhelliwell 
Yeah, makes sense, there is a PR for it that we will review shortly now. We are going through the issues first and will then get to all the PRs after that.
Thanks
Cathal

**Comment by choran** [comment]
Hi @rogerhelliwell 
There was a PR for this which we merged last week and should now be available in latest release.
As a result I will close this issue.
If you still see any issues then please feel free to re-open this again.
Thanks
Cathal
