### ISSUE TITLE
Package assembly rename

### ISSUE THREAD

**Issue by rmtexas** [intercom/intercom-dotnet#59]
"Library.dll" is not a very great name with which to install this assembly.

How about IntercomIo.dll or something similarly imaginative?

Thanks for your efforts, team!

**Comment by rogerhelliwell** [comment]
I would "up vote" this as well.

**Comment by choran** [comment]
Hi @rmtexas 
I think this has been updated now, it should be "Intercom.dll" now.
I will close this but let me know if you still see the old name
Thanks
Cathal
