### ISSUE TITLE
Add Async

### ISSUE THREAD

**Issue by kfrancis** [intercom/intercom-dotnet#6]
I realize it's on the roadmap, but it's relatively simple. Stubbing for a pull request from me.

**Comment by kfrancis** [comment]
@khalilovcmd Can you take a quick glance and see if that's the approach you'd like to take? If so, I can keep working on implementing it throughout.

**Comment by khalilovcmd** [comment]
Thank you @kfrancis for the contribution, and I agree that implementing Async in our case would be doable with our current structure, yet there are few points that we need to consider carefully before proceeding with doing so:

- There is a lot of **DRY**ness that we need to apply to the base `Client` class, and most of its client children classes after introducing Async.

**E.g.:** We are here doing almost [the same thing](https://github.com/kfrancis/intercom-dotnet/blob/b4ba145ffffc1b9aef7d9640b57ab3e29bd9293b/src/Intercom/Core/Client.cs#L202-L281), with the Async differences.

- With deliberately focusing on keeping it DRY, we will need to restructure our code to support this, and redo parts of the unit tests. More code, more maintenance.

- We risk a set of unnoticeable issues while refactoring both the base `Client` and the children clients that could hurt our relatively stable public client.

I am happy to work on this together when we prioritise the Async feature on our roadmap.
