### ISSUE TITLE
Doesn't work in SSIS

### ISSUE THREAD

**Issue by kristylynn9598** [intercom/intercom-dotnet#68]
I have to have an api that is signed, 
Works with in SSIS (VS 2012)
I have worked for 3 days trying to sign, and get all pieces to work. Still not working. 

{"Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)":"RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null"}

That is after getting it signed and in my GAC. 

I have just finished with WorkFront's API, and Replicon's API. Both took about 1 day to get up and working
Here on Day 4 and going back and forth with support, just now told to put in a ticket in another place. 

How many more places must I get handed off too before I can get help that is meaningful and productive?

**Comment by choran** [comment]
Hi @kristylynn9598,
I believe you were speaking to one of our CS team and confirmed that you got this working successfully. I am just going to close this as a result but please re-open if this is incorrect and this is still and issue.
Thanks
Cathal
