### ISSUE TITLE
RestSharp needs TLS set

### ISSUE THREAD

**Issue by thevalyreangroup** [intercom/intercom-dotnet#70]
After hours of trying to figure out why my POST request to the messaged endpoint was not working and not throwing any exception, i finally figured it out by finding this issue on RestSharp's repo.

You have to set the SecurityProtocol to use TLS.  Is everyone else just using HTTP instead of secure?  I'm not sure how anyone got this SDK to work if not.  Any other insight is appreciated.

https://github.com/restsharp/RestSharp/issues/942

`protected virtual IRestClient BuildClient()
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
            
            RestClient client = new RestClient(URL);

            if (!String.IsNullOrEmpty (AUTH.AppId) && !String.IsNullOrEmpty (AUTH.AppKey))
                client.Authenticator = new HttpBasicAuthenticator (AUTH.AppId, AUTH.AppKey);
            else
                client.Authenticator = new HttpBasicAuthenticator (AUTH.PersonalAccessToken, String.Empty);

            return client;
        }`

**Comment by choran** [comment]
Hi @thevalyreangroup 
I think we had a temporary issue after updating API setting which impact TLS configuration.
This issue should now be resolved
I will close this for now as other customer confirmed at the time that the issue was also resolved.
but please re-open in case this was unrelated to the temporary issue.
Thanks
Cathal

**Comment by tekook** [comment]
Hi @choran,

just started using Restsharp and ran into this exact issue again.
Using V 106.2.1 with .Net 4.5.2.
Without the Lines: ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

All my connections get closed.

**Comment by Imbaker1234** [comment]
Where precisely does the Service Point Manager get set? I'm working with generated SwaggerHub clients (That need a lot of fixing after generating) and I can't seem to find where to include the ServicePointManager. What is it a property of?

**Comment by tekook** [comment]
I’m sorry, this is too long ago. 
I moved to Flurl, it is way easier than ReatSharp. 

It does not offer a swagger client, but the rest sharp client of swagger never really worked out of the box.
