### ISSUE TITLE
Bug with company plan

### ISSUE THREAD

**Issue by martinmasse** [intercom/intercom-dotnet#72]
Hi,

There is a bug in the latest version.

https://github.com/intercom/intercom-dotnet/blob/master/src/Intercom/Clients/CompanyClient.cs

Line 193

if (company.plan != null)
   plan = company.name;

should be

if (company.plan != null)
    plan = company.plan;

**Comment by ravtakhar** [comment]
Same issue had to revert back a version.

**Comment by choran** [comment]
Hi @martinmasse 
We just shipped an update which should resolve this issue.
Let me know if you are still having issues with the company plan attribute.
For now I will close this issue but as noted, feel free to re-open if you think the update did not resolve this issue.
Thanks
Cathal
