### ISSUE TITLE
Cannot use UserClient.Update() without force passing a companies object

### ISSUE THREAD

**Issue by frankfuu** [intercom/intercom-dotnet#75]
After updating to the latest Nuget package 1.0.27

https://www.nuget.org/packages/Intercom.Dotnet.Client/1.0.27

I'm no longer able to use the `UsersClient.Update()` call without force parsing a `companies` object

My workaround is to just supply a dummy `companies` object as follows
```
UsersClient.Update(new User() {
      user_id = subscriberid.ToString()
    , email = email , custom_attributes = attributes                
    , companies = new List<Company>() { new Company() { company_id = "new_company" } } 
});
```

Is this by design?

**Comment by markalanevans** [comment]
@frankfuu what happensif you don't set it. 

From here:
https://github.com/intercom/intercom-dotnet/blob/master/src/Intercom/Clients/UsersClient.cs#L409-L440

It looks like it just sends an empty company.

**Comment by frankfuu** [comment]
If i don't set the `companies` object with dummy data. I get an exception. 
```
{"Exception of type 'Intercom.Exceptions.ApiException' was thrown."}
```

And the error message
```
{
  "type": "error.list",
  "request_id": null,
  "errors": [
    {
      "code": 422,
      "message": "invalid companies data structure: must be an array"
    }
  ]
}
```

**Comment by markalanevans** [comment]
@frankfuu  you are right, the data type is a list of companies.

This line https://github.com/intercom/intercom-dotnet/blob/master/src/Intercom/Clients/UsersClient.cs#L409

Should  be
```
var companies = new List<Company>();
```

Just submit a PR for it. it's a quick fix.

**Comment by frankfuu** [comment]
Could it be that if Line [411 ](https://github.com/intercom/intercom-dotnet/blob/master/src/Intercom/Clients/UsersClient.cs#L411)doesn't execute then the `new object()` object in line [409 ](https://github.com/intercom/intercom-dotnet/blob/master/src/Intercom/Clients/UsersClient.cs#L409)get's passed into line [432](https://github.com/intercom/intercom-dotnet/blob/master/src/Intercom/Clients/UsersClient.cs#L432)?

**Comment by frankfuu** [comment]
@markalanevans. Ok sure thing

**Comment by frankfuu** [comment]
Just [created a PR here](https://github.com/intercom/intercom-dotnet/pull/76)

**Comment by choran** [comment]
Thanks for submitting the PR, will take a look as soon as I can
Thanks again
Cathal

**Comment by nvivo** [comment]
When will the fix be released?

**Comment by garethbrown** [comment]
Ditto. Would be nice to get this merged please.

**Comment by choran** [comment]
Hi @frankfuu, @markalanevans, @nvivo, @garethbrown 
Apologies for the delay here, Just merged this in now and it should now be available on latest version.
Thanks for the PR.
I tested this and I was able to create users without needing to provide a company. So I will close this for now but please let me know if you are still encountering issues with updating/creating users with companies.
Thanks again
Cathal
