### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by stephenstroud** [intercom/intercom-dotnet#77]
Are contacts leads?

**Comment by EdBlankenship** [comment]
@stephenstroud:  Yep!  They used to be called `contacts` and so the REST APIs still call them `contacts` as well.

**Comment by choran** [comment]
Yeah, this is a little confusing, as noted, the endpoint on the REST API is contacts. But we should clarify that in the README.
I will close this for now but as always feel free to reopen should you have any other questions/clarifications
Cathal
