### ISSUE TITLE
Requesting notes for user after updating user_id fails

### ISSUE THREAD

**Issue by jopierrelerm** [intercom/intercom-dotnet#8]
I imported users from mailchimp into intercom. None of these users had a "user_id" set, only "email".

After updating the user via the api and set the "user_id" field, the one issue I'm having now is that listing notes by using the "user_id" parameter throws an exception as the check is done in the api if the "user_id" field is set to use the "id" field of the user object. However this seems to not be able to do a lookup and match the user with the "user_id" and "id" field:

![image](https://cloud.githubusercontent.com/assets/1333733/15421665/3e1b9484-1e7d-11e6-8007-5188cdab0190.png)

This can be found in NotesClient.cs in List method

**Comment by jopierrelerm** [comment]
Im only passing the "user_id" field now for the lookup and this id is set on my user when I look inside of the user profile on app.intercom site

![image](https://cloud.githubusercontent.com/assets/1333733/15421757/add27a90-1e7d-11e6-9d7e-56d9376bb7d2.png)

**Comment by khalilovcmd** [comment]
Thank you @jopierrelerm very much for reporting this issue 👍  I have created a hot fix to fix the issue, and the Nuget package is on its way to production.

The issue was related to misinterpretation of the Notes endpoint of our developers documentation, and it will be fixed too.

**Comment by khalilovcmd** [comment]
Please note, that this will be a breaking change for the `NotesClient`. Yet, I have chosen not to update the Major version to 2.0.0 just yet.

**Comment by jopierrelerm** [comment]
Ok cool thanks
