### ISSUE TITLE
Company doesn't support website property

### ISSUE THREAD

**Issue by juliancarrivick** [intercom/intercom-dotnet#82]
As described in the [API docs](https://developers.intercom.com/v2.0/reference#company-model), there is a website property on a company, however as can be seen on [Company.cs](https://github.com/intercom/intercom-dotnet/blob/master/src/Intercom/Data/Company.cs), this is not available on the C# model.

**Comment by choran** [comment]
Hi @juliancarrivick 
Yes, thanks for noting this, there were a few attributes recently added to the company model which we have not yet updated on all SDKs.
We are trying to update all our SDKs for this but I cannot provide a timeline for this at present.
If you would like to provide a PR for this we can review that also. We just note that this is an option for customers that can help with specific SDKs.
If not np, like I said, we do aim to update this on all SDKs.

Cheers
Cathal

**Comment by juliancarrivick** [comment]
Thanks Cathal, not a blocker for me so I'll try to do a pull request if I find time (I'll let you know if I start), otherwise it can wait until the update :)

**Comment by kmossco** [comment]
@juliancarrivick it seems that there are a few fields from the company model missing, and I was looking into adding them. However, if you're interested in doing this yourself I am more than happy to either review it or tag-team. 🙏

**Comment by juliancarrivick** [comment]
@kmossco Unfortunately I'm probably not going to get time to do this in the near future sorry :/

**Comment by kmossco** [comment]
@juliancarrivick no worries at all, thank you so much for flagging this! I'll get to it then. 😉

**Comment by kmossco** [comment]
Fixed by #86. Thank you so much for flagging this @juliancarrivick! 🤜 🤛
