### ISSUE TITLE
Company tags are not supported when viewing a company

### ISSUE THREAD

**Issue by thewheat** [intercom/intercom-dotnet#85]
When viewing a company via the API, tags on the company are returned as seen in the API output below

![image](https://user-images.githubusercontent.com/892961/32473679-cccbc0ec-c3a3-11e7-81a4-8a09f7201e76.png)

But the current .NET SDK does not support retrieving them for companies
![image](https://user-images.githubusercontent.com/892961/32473805-4d473bf2-c3a4-11e7-88ad-a1b9190685a0.png)

The User model currently supports this (indicated above and has a tags list in the model itself)
https://github.com/intercom/intercom-dotnet/blob/9965539d4ca5efec7e975ca3de896d196e922e2b/src/Intercom/Data/User.cs#L42

**Comment by shaQuantum** [comment]
It would save lot of network calls if user and company can be tagged on saving user and customer.

**Comment by kmossco** [comment]
Related to #82

**Comment by kmossco** [comment]
This issue will be fixed with PR #97. Waiting for some testing before merging.

**Comment by kmossco** [comment]
This is now fixed in the new version. 🎉
