### ISSUE TITLE
Company tag action does not currently support targeting by company_id

### ISSUE THREAD

**Issue by theandrewykim** [intercom/intercom-dotnet#87]
Tagging a company with a company_id

Returns a 404. Currently the call is not sending any company data to Intercom on POST.

Labeling as a bug, as this behavior is currently documented.

`tagsClient.Tag("new_tag", new List<Company>() { new Company() { id =  INTERCOM_ID } });`

`tagsClient.Tag("new_tag", new List<String>() { INTERCOM_ID }, TagsClient.EntityType.Company);`

Seem to work when specifically referencing the internal Intercom Id

**Comment by thewheat** [comment]
Digging into this, the code extracts just the `id` / Intercom ID value in several locations

- https://github.com/intercom/intercom-dotnet/blob/c95b92e0d56edc67d608478b89ff26a6e279db5e/src/Intercom/Clients/TagsClient.cs#L175
- https://github.com/intercom/intercom-dotnet/blob/c95b92e0d56edc67d608478b89ff26a6e279db5e/src/Intercom/Clients/TagsClient.cs#L230-L243
- https://github.com/intercom/intercom-dotnet/blob/c95b92e0d56edc67d608478b89ff26a6e279db5e/src/Intercom/Clients/TagsClient.cs#L292
- https://github.com/intercom/intercom-dotnet/blob/c95b92e0d56edc67d608478b89ff26a6e279db5e/src/Intercom/Clients/TagsClient.cs#L325-L338

**Moving forward**
- Update Readme to make it clear that the ID is an Intercom ID (thus we should format the text to be similar to a regular Intercom ID)
- Support tagging by `company_id`, `email` and `user_id` as it is [supported in the docs](https://developers.intercom.com/reference#tag-or-untag-users-companies-leads-contacts)

>Users can be tagged by supplying a users array. The array contains objects identifying users by their `id`, `email` or `user_id` fields.

> Companies can be tagged by sending a companies array. The array contains objects identifying companies by their `id` or `company_id` fields.

**Comment by kmossco** [comment]
Should be fixed by PR #91. Waiting on a review. 👍
