### ISSUE TITLE
Unable to remove a company when updating a user

### ISSUE THREAD

**Issue by juliancarrivick** [intercom/intercom-dotnet#92]
Rather than using the UsersClient.RemoveCompanyFromUser method, I would like to remove the company when performing a user update as described [here](https://developers.intercom.com/v2.0/reference#companies-and-users).

I would expect that setting the remove flag on a company that is in the company list of a user would do this, however the remove flag does not get passed into the generated JSON as seen [here](https://github.com/intercom/intercom-dotnet/blob/ce2f6184b24d710c05122d4c55d6f9f19f5c11ca/src/Intercom/Clients/UsersClient.cs#L413)

**Comment by kmossco** [comment]
Thank you for reporting this @juliancarrivick! That definitely needs to be fixed. Do you want to cook up a PR for this? Otherwise I can try and get it sorted as soon as possible. 👍

**Comment by juliancarrivick** [comment]
@kmossco I should be able to get a pull request in :)
