### ISSUE TITLE
Replying to Users Last Conversation not currently supported

### ISSUE THREAD

**Issue by thewheat** [intercom/intercom-dotnet#95]
The API allows [replying to the last conversation of a user](https://developers.intercom.com/reference#replying-to-users-last-conversation) but [AdminConversationReply.cs](https://github.com/intercom/intercom-dotnet/blob/cf1388945f8361e61873b59adc12bdfc7eefc7d5/src/Intercom/Data/AdminConversationReply.cs) does not seem to expose ways to identify the user

Tested and possible identifiers are `intercom_user_id`, `email` and `user_id` (below shows using `user_id`)

![image](https://user-images.githubusercontent.com/892961/34664433-d88790ae-f496-11e7-9cfc-8b90a3c9d807.png)

**Comment by kmossco** [comment]
I'll be finishing the move to netStandard 2.0 this week, and then will focus on bringing feature parity to the /users endpoint. If anyone wants to give this a try it would be perfect. 👌
